/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    InteractiveGridPattern: typeof import('./src/components/inspira_ui/InteractiveGridPattern.vue')['default']
    LoadingApp: typeof import('./src/components/UI/LoadingApp.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    PdfInspector: typeof import('./src/components/PdfInspector.vue')['default']
    PrimeButton: typeof import('./src/components/prime_vue/PrimeButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/layout/SideMenu.vue')['default']
    StarsBackground: typeof import('./src/components/inspira_ui/StarsBackground.vue')['default']
  }
}
